### ISSUE TITLE
No data on page

### ISSUE THREAD

**Issue by phoenix-blue** [basnijholt/addon-otmonitor#13] opened 2021-01-01 18:39 UTC
Hi,

I have install the addon without problems and setup the "Configuration" and runs the addon. 
In the logfile I get no error's, but the otmonitor page don't receive any info from the otgw.

What do I wrong and is there anything I can check?

**Comment by fliphess** [comment] 2021-04-03 23:59
@phoenix-blue It's been a while since this you posted this issue and a lot has changed since then. 
I know of several fixxes that have been issued in otmonitor itself that help avoid white pages if the OTGW cannot be connected well. 

If you still get white pages, try to reload the repository and rebuild the container and check if your OTGW is connected to the wifi/ethernet and can be accessed by otmonitor. 

(You can verify this by connecting to the OTGW using `telnet` or `nc`. )

I'm closing this issue for now, but feel free to ask for it to be reopened if you are convinced this is an issue caused by a bug in the addon.

**Closed by fliphess** 2021-04-03 23:59 UTC
